### ISSUE TITLE
How to list repositories?

### ISSUE THREAD

**Issue by JorenZ** [mittwald/goharbor-client#107]
**Describe your request**
I would like to list Harbor repositories using the Harbor client.
I could not find how to do this:

* the endpoint gets scraped: `ListRepositories` functions calling `GET /projects/{project_name}/repositories` exist in the code.
  * `apiv2.internal.api.client.repository.Client.ListRepositories` exists but you cannot access this from outside the package, I think?

(This issue is identical to #99 except it concerns a different endpoint.)

**Comment by fnxpt** [comment]
+1 for this, I also don't see any way to get the tags, it would be nice to have an overall of what's currently implemented

**Comment by elenz97** [comment]
Hey @JorenZ, @fnxpt 

I've prepared a [PR](https://github.com/mittwald/goharbor-client/pull/122) for the `repository` client.

> @fnxpt
> +1 for this, I also don't see any way to get the tags, it would be nice to have an overall of what's currently implemented

Addition of an `artifact` will be taken care of in the related issue: #106 :+1:

**Comment by janosmiko** [comment]
+1 for this
