### ISSUE TITLE
List more than 10 Projects /Robot accounts when using goharbor-client

### ISSUE THREAD

**Issue by Candy93j** [mittwald/goharbor-client#113]
**Describe the bug**
I would like to list Harbor Projects and Robot Accounts using this Harbor client.
I could not find how to do list more than 10 projects/robot accounts using `ListProjects()` or `ListRobotAccounts()`. 

It is possible to assign page/ page size parameters in the internal package `V2Client.Robot.ListRobot()` \ `V2Client.Project.ListProjects()`. Is it possible to use this functionality in the goharbor-client?

**Expected behavior**
- Possibility to list more than 10 project/robots when using `ListProjects()` or `ListRobotAccounts()`

**Comment by elenz97** [comment]
Hey @Candy93j,
thanks for opening this issue!

With the [v5.0.0 release](https://github.com/mittwald/goharbor-client/releases/tag/v5.0.0), you can now define custom options when initializing a new client. Via the [`Options`](https://github.com/mittwald/goharbor-client/blob/master/apiv2/pkg/config/options.go#L7) struct, you can set the desired `PageSize` (note: a maximum of 100 is enforced by the Goharbor API).

To get you started, see the example below (showcases the use of the legacy & new robot API):

```go
func ListRobots() {
	harborClient = NewRESTClientForHost(
		"core.harbor.domain",
		"admin",
		"password",
		config.Options{
			PageSize: 100,
		},
	)

	// Using the legacy 'robot' API (supported until Harbor v2.4.0)
	robots, err := harborClient.ListProjectRobotsV1(ctx, "test-project")
	if err != nil {
		panic(err)
	}

	for robot := range robots {
		// your logic here
		_ = robot
	}

	// Using the new API
	robots, err := harborClient.ListRobotAccounts(ctx)
	if err != nil {
		panic(err)
	}

	for robot := range robots {
		// your logic here
		_ = robot
	}
```
