### ISSUE TITLE
i can not find any examples in this project

### ISSUE THREAD

**Issue by lengxugz** [mittwald/goharbor-client#123]
i can not find any examples in this project , can you make some examples?

**Comment by elenz97** [comment]
Hey @lengxugz 
thanks for opening this issue.

To get you started, please have a look at [`apiv2/client_test.go`](https://github.com/mittwald/goharbor-client/blob/master/apiv2/client_test.go) (assuming you want to use the `v2` client).

For example, in [ExampleNewRESTClient_withOptions()](https://github.com/mittwald/goharbor-client/blob/master/apiv2/client_test.go#L68), a harbor client is constructed and later on used to list all projects (equivalent to`GET /projects`).

Please also have a look at our [`harbor-operator`](https://github.com/mittwald/harbor-operator) project.
It utilizes `goharbor-client` to reconcile harbor API resources as Kubernetes resources.

HTH

**Comment by lengxugz** [comment]
thanks
