### ISSUE TITLE
The wrong username and password did not catch the error, the error log in harbor.v2.5.1.tar.gz is as follows

### ISSUE THREAD

**Issue by testwill** [mittwald/goharbor-client#136]
2022-07-06T06:53:45Z [ERROR] [/server/middleware/security/basic_auth.go:72][client IP="192.168.122.123" requestID="2466ffd6-fc12-47a5-b888-1d69dce44a98" user agent="Go-http-client/1.1"]: failed to authenticate user:testt, error:Failed to authenticate user, due to error 'Invalid credentials'

**Comment by elenz97** [comment]
Hey @testwill, thanks for opening this issue.

First off, please verify that the auth information you use is correct. Also, can you provide a small example how you instantiated the client?

**Comment by testwill** [comment]
package main

import (
	"context"
	"crypto/tls"
	"fmt"
	"github.com/mittwald/goharbor-client/v5/apiv2"
	"github.com/mittwald/goharbor-client/v5/apiv2/pkg/config"
	"net/http"
	"net/url"
)

type Repository struct {
	Id     int64  `json:"id"`
	Usr    string `json:"username"`
	Passwd string `json:"passwd"`
	Host   string `json:"host"`
	Scheme string `json:"scheme"`
	Type   string `json:"type"`
	HostId string `json:"host_id"`
	IP     string `json:"ip"`
}

func main() {
	http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}

	fmt.Println("this is a test")
	repo :=Repository{0, "admin", "Harbor112345", "192.168.10.194:443", "https", "Harbor", "", ""}
	 harbor := new(HarborInfo)
	err :=harbor.Init(&repo)
	if err != nil {
		fmt.Println(err.Error())
	}
}

func UrlSplice(scheme, host, path string) string {
	u := url.URL{
		Scheme:      scheme,
		Opaque:      "",
		User:        nil,
		Host:        host,
		Path:        path,
		RawPath:     "",
		ForceQuery:  false,
		RawQuery:    "",
		Fragment:    "",
		RawFragment: "",
	}

	return u.String()
}
type HarborInfo struct {
	cfg    *Repository
	client func(params ...interface{}) *apiv2.RESTClient
}

func (h *HarborInfo)Init(repos *Repository) error {

	h.client = func(params ...interface{}) *apiv2.RESTClient {
		var opts *config.Options
		for _, v := range params {
			switch vv := v.(type) {
			case *config.Options:
				opts = vv
			}
		}

		client, err1 := apiv2.NewRESTClientForHost(UrlSplice(repos.Scheme, repos.Host, "/api/v2.0"), repos.Usr, repos.Passwd, opts)
		if err1 != nil {
			fmt.Println("err :", err1.Error())
		}
		return client
	}

	c := h.client(&config.Options{
		PageSize: 0,
		Page:     0,
	})
	ctx := context.Background()
	_, err := c.GetHealth(ctx)
	return err
}

**Comment by testwill** [comment]
Harbor112345  password error,  correct password  Harbor12345

**Comment by testwill** [comment]
func (a *Client) GetHealth(params *GetHealthParams, authInfo runtime.ClientAuthInfoWriter) (*GetHealthOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetHealthParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getHealth",
		Method:             "GET",
		PathPattern:        "/health",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetHealthReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})


.....

where the error occurred

**Comment by elenz97** [comment]
Hey @testwill, thanks for the follow-up. 
> Harbor112345 password error, correct password Harbor12345
Was this the only error you received? Based on the other information you sent i cannot conclude to an actual error in this library.

**Comment by testwill** [comment]
failed to authenticate user:admin, error:Failed to authenticate user, due to error 'Invalid credentials' ,this error From the harbor core component。harbor does not send authentication error messages。
