### ISSUE TITLE
Error while creating a Replication Rule

### ISSUE THREAD

**Issue by eduartua** [mittwald/goharbor-client#146]
**Describe your request**
Hi all, I'm trying to create a replication rule using the Method `NewReplicationPolicy` which is throwing:
`[POST /replication/policies][400] createReplicationPolicyBadRequest  &{Errors:[0xc00039e5a0]`
What's the best way to find out the specific part causing the error?

This is what I'm returning when calling the mentioned method
```
return s.Client.NewReplicationPolicy(
		ctx,
		policy.DestRegistry,
		nil,
		policy.ReplicateDeletion,
		policy.Override,
		policy.Enabled,
		policy.Filters,
		policy.Trigger,
		policy.DestNamespace,
		policy.Description,
		policy.Name)
```

The `filters` I'm passing in:
```
rp.Filters = []*model.ReplicationFilter{
		{
			Decoration: "",
			Type:       "resource",
			Value:      rule.FilterType,
		},
	}
```
Where `rule.FilterType` has the value of `image`

The `trigger` is:
```
	rp.Trigger = &model.ReplicationTrigger{
		TriggerSettings: &model.ReplicationTriggerSettings{Cron: ""},
		Type:            rule.Trigger,
	}
```

Where `rule.Trigger` has the value of `event_based`.

All the values are correct (AFAICT). I'm getting the `dest` and `src` registry using the `GetRegistryById` and the `ListRegistries` respectively.

I'm inspecting the error type and I'm getting:
`error type: *replication.CreateReplicationPolicyBadRequest`

Which is from an internal package type and I cannot use it to inspect further.

I would appreciate any help.

**Comment by elenz97** [comment]
Hey @eduartua, thanks for opening this issue. I've tried reproducing your issue with similar parameters but could not see an error. Can you inspect the (debug) logs of the `harbor-core` component? They should tell you what exactly leads to the error.

**Comment by eduartua** [comment]
This is the only thing I can see in `habor-core` logs:
```
2022-09-06T06:15:02Z [INFO] [/server/middleware/security/robot.go:71][requestID="b0f8b2a684b1d0efd3c1c3...."]: a robot security context generated for request GET /api/v2.0/replication/policies
2022-09-06T06:16:04Z [INFO] [/server/middleware/security/robot.go:71][requestID="447afb463a8c11d09cbf68...."]: a robot security context generated for request GET /api/v2.0/registries/0
2022-09-06T06:16:04Z [INFO] [/server/middleware/security/robot.go:71][requestID="f9abb671722e423abfcefc4..."]: a robot security context generated for request POST /api/v2.0/replication/policies
2022-09-06T06:18:31Z [INFO] [/server/middleware/security/robot.go:71][requestID="c14a31280dc2305701bb86..."]: a robot security context generated for request GET /api/v2.0/registries/0
2022-09-06T06:18:31Z [INFO] [/server/middleware/security/robot.go:71][requestID="581dbb46ced3ff31123a...."]: a robot security context generated for request POST /api/v2.0/replication/policies
2022-09-06T06:19:36Z [INFO] [/server/middleware/security/robot.go:71][requestID="06079eddfc58ea4239fb48...."]: a robot security context generated for request GET /api/v2.0/registries/0
2022-09-06T06:19:36Z [INFO] [/server/middleware/security/robot.go:71][requestID="fc83da1ecb1680c3f8ccbd9...."]: a robot security context generated for request POST /api/v2.0/replication/policies

If I'm getting this error: 
` [POST /replication/policies][400] createReplicationPolicyBadRequest  &{Errors:[0xc00022c1e0]}`
Then the problem should be the policy object, right?

**Comment by elenz97** [comment]
Hey @eduartua, thanks for following up on this.

> Then the problem should be the policy object, right?

It's hard to tell, honestly. You can try enabling the debug log of the `core` component to maybe get some extensive error messages. There is quite a lot of validation going on for `policy` objects - you might want to check with the [upstream source](https://github.com/goharbor/harbor/blob/98cef43ead677da277c2bd4a6b1a25461ee4078c/src/controller/replication/model/model.go#L63) (for your current version) to see if the error actually is on your side or due to an error in Harbor's validation.

HTH

**Comment by eduartua** [comment]
Using the log level `debug` I get:
```
2022/09/06 15:32:54 Model:
2022/09/06 15:32:54 r.r: sub, obj, act
2022/09/06 15:32:54 p.p: sub, obj, act, eft
2022/09/06 15:32:54 e.e: some(where (p_eft == allow)) && !some(where (p_eft == deny))
2022/09/06 15:32:54 m.m: g(r_sub, p_sub) && keyMatch2(r_obj, p_obj) && (r_act == p_act || p_act == '*')
2022/09/06 15:32:54 g.g: _, _
2022/09/06 15:32:54 Policy:
2022/09/06 15:32:54 p: sub, obj, act, eft: [[robot$replication /system/replication * allow] [robot$replication /system/registry * allow] [robot$replication /system/replication-policy * allow]]
2022/09/06 15:32:54 g: _, _: []
2022/09/06 15:32:54 Role links for: g
2022/09/06 15:32:54 
2022/09/06 15:32:54 Request: robot$replication, /system/registry, list ---> true
```

**Comment by eduartua** [comment]
@elenz97 I figured out the problem. It turns out I was passing `nil` for the destination registry. The right value to pass is an empty `Registry` struct (`&model.Registry{}`).

Another question I have is:
Is it possible to set the `Flattening` option in the Destination section?
![flatten2022-09-06_11-12](https://user-images.githubusercontent.com/3302523/188684570-730b9c4b-d314-4c50-912c-c2661c291919.png)

**Comment by eduartua** [comment]
@elenz97  I see what's missing. See the `NewReplicationPolicy` method:
```
// NewReplicationPolicy creates a new replication policy with the given arguments.
func (c *RESTClient) NewReplicationPolicy(ctx context.Context, destRegistry, srcRegistry *modelv2.Registry,
	replicateDeletion, override, enablePolicy bool,
	filters []*modelv2.ReplicationFilter, trigger *modelv2.ReplicationTrigger,
	destNamespace, description, name string,
) error {
	params := &replicationapi.CreateReplicationPolicyParams{
		Policy: &modelv2.ReplicationPolicy{
			Description:               description,
			DestNamespace:             destNamespace,
			DestNamespaceReplaceCount: nil,
			DestRegistry:              destRegistry,
			Enabled:                   enablePolicy,
			Filters:                   filters,
			Name:                      name,
			Override:                  override,
			ReplicateDeletion:         replicateDeletion,
			SrcRegistry:               srcRegistry,
			Trigger:                   trigger,
		},
		Context: ctx,
	}

	params.WithTimeout(c.Options.Timeout)

	_, err := c.V2Client.Replication.CreateReplicationPolicy(params, c.AuthInfo)
	if err != nil {
		return handleSwaggerReplicationErrors(err)
	}

	return nil
}
```
It has hardcoded the `DestNamespaceReplaceCount: nil,` value.

**Comment by eduartua** [comment]
@elenz97 I'll close this issue then. The logic to add the `DestNamespaceReplaceCount` can be discussed in another issue.
