### ISSUE TITLE
How to get labels from ListArtifacts interface

### ISSUE THREAD

**Issue by alvin008** [mittwald/goharbor-client#155]
I found ListArtfiacts interface response labes is null. When i try to config the parameter "SetWithLabe" to "True", it shows artifacts package is internal. How can i fix it?

**Comment by Faione** [comment]
Same question while using `GetArtifact`. Will you provide a method like `ListArtifactsWithLabels`?  now  there is no way i can find to get labels about Artifact

**Comment by alireza-mht** [comment]
This would be a very useful feature to have the labels. Is there a plan to include it?

**Comment by elenz97** [comment]
Hey, thanks for opening the issue :+1: I see no reason why we should'nt return labels when using `ListArtifacts()` anyways, so we've added the support for it in the most recent release, [v5.5.4](https://github.com/mittwald/goharbor-client/releases/tag/v5.5.4)
