### ISSUE TITLE
RESTClient does not implements the Client interface

### ISSUE THREAD

**Issue by sergimrz** [mittwald/goharbor-client#174]
**Describe the bug**
The RESTClient object does not implements the Client interface

**To Reproduce**
Create a client variable and assign to it a new RESTClient.
example:
`var _ Client = (*RESTClient)(nil)`

**Expected behavior**
The RESTClient object implements the Client interface so we can create proper mocks for it

Fixed on the following PR: https://github.com/mittwald/goharbor-client/pull/172

**Comment by elenz97** [comment]
Thanks for your contribution. Should be fixed with the merge of https://github.com/mittwald/goharbor-client/pull/172 :+1:
