### ISSUE TITLE
`GetProject` returns `ErrProjectNotFound` for any error gotten from the Harbor API

### ISSUE THREAD

**Issue by ennekein** [mittwald/goharbor-client#185]
**Describe the bug**
`GetProject` returns `ErrProjectNotFound` for any error gotten from the Harbor API. 

This code changes the error to `ErrProjectNotFound`: https://github.com/mittwald/goharbor-client/blob/master/apiv2/pkg/clients/project/project.go#L112-L114. The internal `GetProject` function returns a _nil_ response whenever the API returns an error: https://github.com/mittwald/goharbor-client/blob/master/apiv2/internal/api/client/project/project_client.go#L192-L194. This means that any error results in `ErrProjectNotFound` and `handleSwaggerProjectErrors` is never called.

**To Reproduce**
Call `GetProject` with the wrong Harbor credentials in the client.

**Expected behavior**
It should return `ErrUnauthorized` but returns `ErrProjectNotFound`.

Environment:
- `goharbor-client` version: v0.5.5
- `goharbor` version: v2.9.1-5cbb1b01

**Comment by BerndFarkaDyna** [comment]
what an coincident, i stumbled over the exact same problem 2 hours ago and wanted to file it

**Comment by elenz97** [comment]
Hey @ennekein, @BerndFarkaDyna - i've included [a fix](https://github.com/mittwald/goharbor-client/commit/c1da600eb4e308a9e4417441b87aa3258084bcad) for this in the most recent release found here: [v5.5.3](https://github.com/mittwald/goharbor-client/releases/tag/v5.5.3).

**Comment by ennekein** [comment]
Hi @elenz97 thanks for the quick fix!
