### ISSUE TITLE
When will this client support Harbor v2.0 API ?

### ISSUE THREAD

**Issue by sunlianqiang** [mittwald/goharbor-client#53]

**Comment by elenz97** [comment]
Hey @sunlianqiang,

as of now, we have not yet planned on implementing a "v2" version of this client, as the included design changes of the client need to be discussed.
Sadly, I can not give you an estimate release date, but make sure to check around!

**Comment by elenz97** [comment]
Hey @sunlianqiang,

unfortunately i did not mention you on the initial release of [`v2.0.0`](https://github.com/mittwald/goharbor-client/releases/tag/v2.0.0), so this is ment as a follow-up. With that release, we've added support for goharbor's `v2.0` API version. 

From there on, we've by now released [`v3.0.0`](https://github.com/mittwald/goharbor-client/releases/tag/v3.0.0), which supports goharbor's `v2.1` API version.

Please check https://github.com/mittwald/goharbor-client/releases/ to get an overview of our releases. HTH
