### ISSUE TITLE
request examples to use these APIs

### ISSUE THREAD

**Issue by ReyRen** [mittwald/goharbor-client#73]
Hello, can you please give some examples, like operation codes to illustrate some cases in using this API.

Thanks

**Comment by elenz97** [comment]
Hey @ReyRen,

thanks for your question!

We are aware that code samples would add great value to this project, yet I cannot tell exactly when we will start working on them. Any PR (preferably, in the manner of [testable code example](https://golang.org/pkg/testing/#hdr-Examples)) going in this direction is welcome!

In the meantime, please have a look at our [harbor-operator project](https://github.com/mittwald/harbor-operator), which utilizes this client to communicate with harbor instances.
If you're not familiar with Kubernetes operators, the individual controllers (found under [mittwald/harbor-operator/controllers/](https://github.com/mittwald/harbor-operator/tree/v1.2.3/controllers) may be a good place to start (for example, have a look at the [project controller](https://github.com/mittwald/harbor-operator/blob/v1.2.3/controllers/project_controller.go#L107) which runs this client's CRUD methods on harbor projects).

HTH

**Comment by ReyRen** [comment]
@elenz97 , thanks for your warm reply. I will direct to  harbor-operator, which I think is what I want. lol
\Close
