### ISSUE TITLE
Help creating ReplicationPolicies

### ISSUE THREAD

**Issue by fcrespofastly** [mittwald/goharbor-client#83]
**Hep with Replication Policies**

Hey folks!

I'm trying to use the client to automate how we create replication policies. I'm getting an issue that seems to come from swagger itself when I use `NewReplicationPolicy`:

```
"&[] (*[]*legacy.Registry) is not supported by the TextConsumer, can be resolved by supporting TextUnmarshaler interface"
```
I don't understand why it says `*[]*legacy.Registry` since I'm just passing single registry objects.

Not sure if this is related but:

https://github.com/go-swagger/go-swagger/issues/1929

I'm hesitant to open this as a bug, since I'm not really sure if it's on my side, swagger side or your side 😅 . Can I get some hep please?

**Comment by elenz97** [comment]
Hey @fcrespofastly,

thanks for your question!

The error message you provided _does_ look like it originated from swagger, though i've not yet seen it myself.

Perhaps, could you give a short code example or a way to reproduce the above?
Also, which `goharbor-client` / `goharbor` version are you using?

I'd be interested to see what would happen if you `curl`-ed the request against the Harbor API as well.
Generally, an error message like the above should be more descriptive and _at least_ contain a http status code to figure out why it failed.

**Comment by fcrespofastly** [comment]
Hey thanks for your replu @elenz97 !

I just used the `NewReplicationPolicy` call, client version 3.2.0, harbor version 2.1.3. 

I replaced the client with a simple http client and it just works. 🤷🏻‍♂️

**Comment by elenz97** [comment]
As from I've by now tried several scenarios when calling `NewReplicationPolicy`, in which - unfortunately - none lead to the error you described above. As it's hard for me to replicate (no pun intended) the exact behavior, could you please provide a code example (maybe in the style of an integration test like https://github.com/mittwald/goharbor-client/blob/v3.2.0/apiv2/replication/replication_integration_test.go#L30)?

> I replaced the client with a simple http client and it just works. 🤷🏻‍♂️

Please, could you expand on this in a little more detail?

**Comment by fcrespofastly** [comment]
Hey @elenz97 ! Thanks for testing this out!
> Please, could you expand on this in a little more detail?

So I basically created a basic package for the service I'm building that will just send HTTP json requests to harbor API and it worked for me.

I'll try to replace it with your library when I find the time and I'll get back to you, thanks!

**Comment by elenz97** [comment]
Alright - please let us know if you have any other question :+1:
