### ISSUE TITLE
System-level robot accounts API

### ISSUE THREAD

**Issue by StevenReitsma** [mittwald/goharbor-client#85]
**Is your feature request related to a problem? Please describe.**
Version 2.2.0 of Harbor was released today. It includes a new system-level robot account API.
https://github.com/goharbor/harbor/releases/tag/v2.2.0

**Describe the solution you'd like**
I'd like to use this API in the `goharbor-client` library.

**Comment by elenz97** [comment]
Hey @StevenReitsma,

as of now, I cannot give you an estimate when we will start working on migrating to the `v2.2.0` goharbor API.
The upgrade itself should be a straightforward task, as - with the new version - API specifications have (mostly) been renamed and / or moved.

If we have any update, we'll let you know in this issue!

**Comment by axelgobletbdr** [comment]
Do you have a new ETA on this feature by now?

**Comment by elenz97** [comment]
> Do you have a new ETA on this feature by now?

Hey @axelgobletbdr,

unfortunately we do not have any ETA _yet_.
Make sure you are subscribed to this issue for any updates!

**Comment by elenz97** [comment]
@StevenReitsma @axelgobletbdr @shreddedbacon 

With the latest [`v4.0.0` release](https://github.com/mittwald/goharbor-client/releases/tag/v4.0.0) you can now use the new `robot` client :tada: 

The `v4` client library can be installed via `go get github.com/mittwald/goharbor-client/v4/apiv2`.
If you have any further questions feel free to open a [new issue](https://github.com/mittwald/goharbor-client/issues/new/choose)!

**Comment by StevenReitsma** [comment]
Amazing! Thanks for that. I'll try it out real soon.
