### ISSUE TITLE
Does apiv1 support `/repositories` query?

### ISSUE THREAD

**Issue by x1nchen** [mittwald/goharbor-client#93]
**Describe your request**

Hi, 

Does apiv1 support `/repositories` query?

like this request

`https://dockerhub-host/api/repositories?page=1&page_size=15&project_id=2&q=report`

ref https://github.com/goharbor/harbor/blob/v1.10.0/api/harbor/swagger.yaml#L1004-L1045

**Comment by gsakun** [comment]
```
func (a *Client) GetRegistries(params *GetRegistriesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRegistriesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRegistriesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetRegistries",
		Method:             "GET",
		PathPattern:        "/registries",
		ProducesMediaTypes: []string{"application/json", "text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetRegistriesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRegistriesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetRegistries: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}
```
```
func (c *RESTClient) GetRegistry(ctx context.Context, name string) (*model.Registry, error) {
	if name == "" {
		return nil, &ErrRegistryNotProvided{}
	}
	resp, err := c.LegacyClient.Products.GetRegistries(
		&products.GetRegistriesParams{
			Name:    &name,
			Context: ctx,
		}, c.AuthInfo)
	if err != nil {
		return nil, handleSwaggerRegistryErrors(err)
	}

	for _, r := range resp.Payload {
		if r.Name == name {   //Matches only those with the same name
			return r, nil
		}
	}

	return nil, &ErrRegistryNotFound{}
}
```
I also don't understand why the author didn't write the ListRegistries interface,You can wrap one yourself

**Comment by x1nchen** [comment]
> ```
> func (a *Client) GetRegistries(params *GetRegistriesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRegistriesOK, error) {
> 	// TODO: Validate the params before sending
> 	if params == nil {
> 		params = NewGetRegistriesParams()
> 	}
> 	op := &runtime.ClientOperation{
> 		ID:                 "GetRegistries",
> 		Method:             "GET",
> 		PathPattern:        "/registries",
> 		ProducesMediaTypes: []string{"application/json", "text/plain"},
> 		ConsumesMediaTypes: []string{"application/json"},
> 		Schemes:            []string{"http", "https"},
> 		Params:             params,
> 		Reader:             &GetRegistriesReader{formats: a.formats},
> 		AuthInfo:           authInfo,
> 		Context:            params.Context,
> 		Client:             params.HTTPClient,
> 	}
> 	for _, opt := range opts {
> 		opt(op)
> 	}
> 
> 	result, err := a.transport.Submit(op)
> 	if err != nil {
> 		return nil, err
> 	}
> 	success, ok := result.(*GetRegistriesOK)
> 	if ok {
> 		return success, nil
> 	}
> 	// unexpected success response
> 	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
> 	msg := fmt.Sprintf("unexpected success response for GetRegistries: API contract not enforced by server. Client expected to get an error, but got: %T", result)
> 	panic(msg)
> }
> ```
> 
> ```
> func (c *RESTClient) GetRegistry(ctx context.Context, name string) (*model.Registry, error) {
> 	if name == "" {
> 		return nil, &ErrRegistryNotProvided{}
> 	}
> 	resp, err := c.LegacyClient.Products.GetRegistries(
> 		&products.GetRegistriesParams{
> 			Name:    &name,
> 			Context: ctx,
> 		}, c.AuthInfo)
> 	if err != nil {
> 		return nil, handleSwaggerRegistryErrors(err)
> 	}
> 
> 	for _, r := range resp.Payload {
> 		if r.Name == name {   //Matches only those with the same name
> 			return r, nil
> 		}
> 	}
> 
> 	return nil, &ErrRegistryNotFound{}
> }
> ```
> 
> I also don't understand why the author didn't write the ListRegistries interface,You can wrap one yourself

Awesome!!! Thanks.
